### PR TITLE
Extend host module tests

### PR DESCRIPTION
**Pull request by msekania**
Add tests to host module

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the new behavior?

- test for default folder resolution for hosts
- test for default folder resolution for cluster hosts

### CODE REVIEW

**Comment by robin-checkmk** [comment]
@msekania maybe I am misunderstanding, but you basically added a host without an explicit folder, right?
Shouldn't we also add a host with a specific folder and verify, that both of these things yield the correct results?

**Comment by msekania** [comment]
@robin-checkmk, 

> maybe I am misunderstanding, but you basically added a host without an explicit folder, right?

yes, right!

> Shouldn't we also add a host with a specific folder and verify, that both of these things yield the correct results?

There are already hosts with specific folder, but no check that they are created in the requested ones.
I'll add that check too.

**Comment by msekania** [comment]
@robin-checkmk, 

I have included the folder test for hosts with given folder parameter, via host lookup plugin

**Comment by robin-checkmk** [comment]
Awesome, thanks man!

**Pull request merged**
