### PR TITLE
Changed 2.2.0 beta to stable

### PR DESCRIPTION
**Pull request by Max-checkmk**
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [x] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Integration tests run against 2.2.0b8 which isn't downloadable anymore

## What is the new behavior?

- Changed 2.2.0b8 beta to 2.2.0p1 stable
- Changed stable to oldstable (2.1)
- Changed oldstable to ancientstable (2.0)

## Other information

Change is already inside PR #344 and #347 as testing fails without this.
This PR is for a quick integration into master branch. After that the version changes in those 2 other PR can be ignored.

### CODE REVIEW

**Comment by Max-checkmk** [comment]
I have read the CLA Document and I hereby sign the CLA or my organization already has a signed CLA.

**Comment by Max-checkmk** [comment]
recheck

**Comment by Max-checkmk** [comment]
recheck

**Comment by lgetwan** [comment]
There's no 2.2.0p1 package for bionic:
`TASK [rule : Download Checkmk Versions.] *****************************************************************************************************************************************************************************************************************************************
failed: [testhost] (item={'version': '2.2.0p1', 'site': 'stable'}) => {"ansible_loop_var": "item", "changed": false, "dest": "/tmp/checkmk-server-stable.deb", "elapsed": 0, "item": {"site": "stable", "version": "2.2.0p1"}, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "status_code": 404, "url": "https://download.checkmk.com/checkmk/2.2.0p1/check-mk-raw-2.2.0p1_0.bionic_amd64.deb"}
changed: [testhost] => (item={'version': '2.1.0p28', 'site': 'oldstable'})
`

**Review by robin-checkmk — APPROVED** [review]
A manual run of the GitHub Action revealed no issues and the code looks good.

**Pull request merged**
