### PR TITLE
Release 3.4.0

### PR DESCRIPTION
**Pull request by robin-checkmk**
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [x] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the new behavior?

- #440 
- #456 
- #459
- #465
- #427

### CODE REVIEW

**Comment by robin-checkmk** [comment]
@msekania and @Max-checkmk: Can you please take a look at a3dbf379b1536ec9601b9f4c10ff218d473d0aba and let me know if the change seems sound to you? I wanted to improve the tests, but not make big deal out of it. So you just taking a peek if looks sound and giving me a thumbs up should be fine. Thanks! :pray:

**Comment by msekania** [comment]
@robin-checkmk,

Yes, these checks are better.
However, here one takes granted that the error messages from the Ansible remain as they are now. 
Anyway, one only needs to remember that these can be a possible sources of errors and make appropriate adjustments when necessary.

**Comment by robin-checkmk** [comment]
@msekania I do quite like the fact, that the tests will fail, if anything changes. Because then we can understand what exactly is going on and adapt if necessary. Otherwise, we might miss something.

Thanks for your feedback!

**Review by lgetwan — APPROVED** [review]
Looks good to me. Go for it!

**Pull request merged**
