### PR TITLE
More tunable URL for the server

### PR DESCRIPTION
**Pull request by jostmart**
More tunable URL for the server

I put check_mk server behind a proxy which listens to 443 and send requests to the server_port. Therefore I need to be able to use the server without port in the URL

## Pull request type

- [ ] Bugfix
- [x ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?
Port is hardcoded

## What is the new behavior?
Old port are kept as default. But you will be able to override the whole connection string.
-
-

### CODE REVIEW

**Comment by jostmart** [comment]
I have read the CLA Document and I hereby sign the CLA or my organization already has a signed CLA.

**Comment by robin-checkmk** [comment]
recheck

**Comment by robin-checkmk** [comment]
recheck

**Comment by robin-checkmk** [comment]
@jostmart I found the issue: Your commits were made with the name `josmar`, missing the `t`. In this case you need to add the e-mail address used for making those commits to your GitHub account.

**Pull request closed without merging**
