### PR TITLE
Fix server url

### PR DESCRIPTION
**Pull request by Mareise**
The port was missing for the server url for the activation.
The comments in the readme were placed under the wrong commands.

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe):

### CODE REVIEW

**Comment by Mareise** [comment]
I have read the CLA Document and I hereby sign the CLA or my organization already has a signed CLA.

**Comment by Mareise** [comment]
recheck

**Review by robin-checkmk — APPROVED** [review]

**Comment by robin-checkmk** [comment]
Hi @Mareise and thanks for the bug fix!
Just to be 100% certain: The two changes have nothing to do with each other, you just noticed the two problems at the same time, right?

P.S.: The Molecule do fail, but that is an unrelated issue.

**Comment by Mareise** [comment]
Hi robin,

yeah you are right, I just noticed the two problems at the same time.
Thanks for the fast response.

**Comment by robin-checkmk** [comment]
Alright, then I will release this change as a bug fix release within this week.
I just need to take care of one more thing first.

**Pull request merged**
