### PR TITLE
Feature agent windows support

### PR DESCRIPTION
**Pull request by robin-checkmk**
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

There is no support for Windows clients in the agent role.

## What is the new behavior?

We want to introduce Windows support for the agent role.

## Other information

Currently, there are no resources to start developing this. If you have the time and possibilities, have at it. :slightly_smiling_face: 
There are files from another project here, but you should be able to get started from the existing tasks for Linux.
If you have questions, feel free to drop them here.

### CODE REVIEW

**Comment by muehlings** [comment]
I can help with testing later. I have setup almost all current and some older Windows operating systems (Win 10/11, Server 2012 up to Server 2022). I'm sure there are some preparation steps before ansible can manage a windows host.

**Comment by muehlings** [comment]
The preparation of Windows hosts is working in my lab.
The tasks and vars of my playbook and inventory are working, but I had to split and reorganize the Linux parts.
Now I have the problem how I PR this PR or should I use my own branch and make a new PR?

**Comment by robin-tribe29** [comment]
That sounds great!
Did you fork this feature branch, or did you fork `devel`?
Anyway, just open a new PR, and we will take it from there.

**Comment by muehlings** [comment]
I forked from tribe29/ansible-collection-tribe29.checkmk:feature-agent-windows-support for the initial Windows files.

I am absent for the next two weeks, but you can already test with https://github.com/muehlings/ansible-collection-tribe29.checkmk/tree/feature-agent-windows-support

New directory "preparation" is for getting winrm to work.

Other changes are in the agent role.

**Comment by muehlings** [comment]
Hello @robin-tribe29,

can you merge the two PRs into one?

Greetings

**Comment by robin-tribe29** [comment]
@muehlings you mean #187? I would want to see the tests green, then there is probably no harm in merging into this feature branch.

Sorry, we are totally swamped, hence the silence in the project.
Hopefully I can work on all this again within two weeks.

**Comment by robin-tribe29** [comment]
Quick update: This is still in the making, but I am uncertain how to move forward, as I want the role restructuration to be as solid as possible. So for the time being, any and every feedback on the state of this branch is welcome.
I will try to work our some testing to make sure we do not break the role and that we have enough resources to quickly fix issues, if they occur.

**Comment by HaZet1968** [comment]
I can test, too, if necessary. I am very interested in that feature.

**Comment by robin-tribe29** [comment]
@muehlings I rebased this PR on top of the main branch.

I am still not perfectly sure, when and how we will merge this for a release, but I did not forget about this, rest assured. :v:

**Comment by muehlings** [comment]
I have read the CLA Document and I hereby sign the CLA or my organization already has a signed CLA.

**Review by robin-checkmk — COMMENTED** [review]
I am very unhappy with the `preparations` folder. I understand why it is needed, but I do not yet like the location of it. We need to find a better solution here.

Apart from that, this looks mostly fine to me.

**Comment by robin-checkmk** [comment]
I tested the proposed changes against the Linux side of things and cannot find a regression there. So I can greenlight the changes from that site.

However, anyone reading along, please do test this pull request and provide feedback, if you can.

If nothing comes up, @Max-checkmk will finalize work on this PR and we will merge and release it.

**Pull request merged**
