### PR TITLE
Feature/tag group add help

### PR DESCRIPTION
**Pull request by meni2029**
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Currently the "help" is not supported by the tag_group module. It is supported by the API.

## What is the new behavior?

- Adding the "help" attribute in the tag_group module.

## Other information

I just replicated the handling of "topic" in the code. I checked that "help" is supported by the API.

### CODE REVIEW

**Comment by meni2029** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by meni2029** [comment]
recheck

**Comment by meni2029** [comment]
I have read the CLA Document and I hereby sign the CLA or my organization already has a signed CLA.

**Comment by robin-checkmk** [comment]
@meni2029 can you please look at the integration tests and try to fix the issue? It looks like creating a tag group is broken.

**Comment by robin-checkmk** [comment]
@lgetwan I looked at the error and it seems like the REST API can set the help on a tag group, but it cannot get that field. Do you concur? Oder am I misunderstanding something?
If my diagnosis is correct, maybe you have an idea for a workaround here. Worst case, we cannot add support for this into the role just yet.

**Comment by lgetwan** [comment]
@robin-checkmk: I come to the same conclusion.

**Comment by robin-checkmk** [comment]
The `help` attribute will be available starting with Checkmk 2.2.0p18.
@lgetwan do you see a way to implement this in a way, that works for version before and after 2.2.0p18?
Otherwise, we can implement it for Checkmk 2.2.0p18 and later and put a warning message in the docs.

**Comment by robin-checkmk** [comment]
This is being implemented with the rewrite of the `tag_group ` module in #512.
I will therefore close this pull request and ask interested parties to look into the other pull request.
Thanks!

**Pull request closed without merging**
