### PR TITLE
 fix #338 downtime timezone removed when using end_after

### LINKED ISSUE #338: [BUG] downtime removing timezone when using end_after
**Describe the bug**

When using the module `tribe29.checkmk.downtime` with `end_after` and providing a `start_time` with timezone the module is ignoring the timezone.

i.e. the following ansible code creates a downtime for `2023-05-12T13:00:00Z` and so on `2023-05-12T15:00:00+02:00` instead of `2023-05-12T13:00:00+02:00`

```yaml
- name: schedule host downtime
  tribe29.checkmk.downtime:
    ...
    start_time: "2023-05-12T13:00:00+02:00"
    end_after:
      weeks: 1
```

When directly using `start_time` with `end_time` the timezone is used correctly.

**Component Name**

downtime

**Ansible Version**

```console
$ ansible --version
ansible [core 2.12.5.post0]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.13 (default, Jun 24 2022, 15:27:57) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
  jinja version = 2.11.3
  libyaml = True
```

**Checkmk Version and Edition**

```console
2.1.0p27 cee
```

**Collection Version**

Bug found under at least:
```
tribe29.checkmk:0.22.0
tribe29.checkmk:0.21.0
tribe29.checkmk:0.20.0
```

**To Reproduce**
See bug description

**Expected behavior**

The timezone is kept while using `end_after` and so the behavior is consistent across the module.

**Actual behavior**

See bug description

**Minimum reproduction example**

See bug description

**Additional context**

The problem seems to be the following line, which deletes the timezone i.e. `+02:00` and replaces it with `Z`.
https://github.com/Checkmk/ansible-collection-tribe29.checkmk/blob/main/plugins/modules/downtime.py#L201

**Possible Solution**
Instead of modifying the `start_date` and then using `datetime.strptime` there could be used `datetime.fromisoformat(start_time)`.

### PR DESCRIPTION
**Pull request by simonhir**
Fixes #338 by using `datetime.fromisoformat` and `isoformat()` instead of `datetime.strptime`.
This gives the possibility to disable the removal of the timezone from the `start_time`.

Possible issue could be the support of python2 if this is needed for the collection.

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: #338 

## What is the new behavior?

The timezone is not removed from the `start_time` while calculating the `end_time` with `end_after`

### CODE REVIEW

**Comment by simonhir** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by simonhir** [comment]
recheck

**Comment by robin-checkmk** [comment]
Hi @simonhir and thanks for your contribution!
I will have some look into the CLA bot thingy, why he did not like your signature.
Also, someone will take a peek at the code, before we can merge.
But I am positive that this PR will make it into the next release. :v:

**Comment by englertor** [comment]
recheck

**Review by lgetwan — APPROVED** [review]
I successfully tested your changes. Thanks for your contribution! :-)

**Pull request merged**
