### PR TITLE
New Cluster Module

### PR DESCRIPTION
**Pull request by msekania**
Create/Modify/Delete cluster host of given nodes.
Stand alone module to reduce complexity of the host module.

See #518 

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [X] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Currently there is no any module that manages creation of the host as an aggregate cluster of the given list of nodes.
See #518 

## What is the new behavior?

- Creates cluster host of given nodes, with the given name and folder
- Modifies list of cluster nodes
- Manages attributes of the given cluster host
- Deletes specified cluster host

### CODE REVIEW

**Comment by msekania** [comment]
Can be also included in host module introducing the new state
`state: cluster`

Not quite sure whether increasing complexity of the host module is feasible.
On the other hand rest of the management is done by host module.

**Comment by robin-checkmk** [comment]
My gut feeling says, I would rather see it in the host module, but I cannot judge the complexity code-wise. Also, I am not yet sure, if my gut feeling is a good indicator, as I prefer fact based decisions.

> On the other hand rest of the management is done by host module.

@msekania does this mean, that one needs both this new module and the `host` module to manage cluster hosts, or does it mean, that you duplicated the code?

**Comment by msekania** [comment]
@robin-checkmk,


@robin-checkmk,

> @msekania does this mean, that one needs both this new module and the `host` module to manage cluster hosts, or does it mean, that you duplicated the code?

Yes, I have duplicated the code in the last two **working** iterations.

Concerning including it to host module, after the last test I got an idea how one can do it.
It will require careful testing though.
I'll try to prepare clean extension to host module and make PR against #562

**Comment by robin-checkmk** [comment]
@msekania as #562 is progressing, where do we stand? Should we close this PR, or should we keep it open, in case incorporating the cluster management in the `host` module does not work?

**Comment by msekania** [comment]
@robin-checkmk, I'll close this PR. I have another version of cluster module which will build on #562.
So as soon as it is accepted I can carry out few adjustments in the module which I have already prepared in the forked version and make a PR with cluster extensions for host module.

**Pull request closed without merging**
