### PR TITLE
Better rule arguments parsing and default values

### PR DESCRIPTION
**Pull request by geof77**
This PR improves arguments checking and documentation:

* detailed documentation for all supported parameters
* update the examples and their syntax
* apply default values so the user can omit _conditions_ and _properties_ suboptions or even entirely
* validate the format of _folder_ and  _documentation_url_
* enforce complete expressions for _host_name_, _host_tags_, _host_labels_ and _service_labels_
* take care of parameters with empty values causing API errors

Related issues: #181 #182 

## Pull request type
- [ ] Bugfix
- [x] Feature
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe):

### CODE REVIEW

**Comment by geof77** [comment]
I'm trying to fix the integration tests, even tried with my own version of get_existing_rules, but it still fails on the test case shown below.

I found there is a test rule with a host_name condition that looks invalid.  As you can see in the request, the match_on field is empty, but the operator is "one_of". For me that means "one of [nothing]", it does not make sense, unless it has a special (undocumented?) usage.

I wonder why this specific test case is present. @diademiemi, @lgetwan, @robin-tribe29 : anybody knows why? Or can ask somebody who may know :) ?

However:
* The API accepts it, so it is not "invalid"
* the API returns the host_name field as empty (it does not return the field if it's really empty)
* the get_existing_rule comparison fails so the rule is always created (status "changed" => failed integration test)
* In the GUI I see the message "This rule does never apply due to an empty list of explicit hosts!"

I think this situation should be disallowed in Ansible tasks enforcing a non-empty match_on field together with a valid operator.  

Of course the test case should be modified.

```
   "request": {
        "conditions": {
            "host_labels": [],
            "host_name": {
                "match_on": [],
                "operator": "one_of"
            },
            "host_tags": [],
            "service_labels": []
        },
        "folder": "/",
        "properties": {
            "comment": "Warning at 80%\nCritical at 90%\n",
            "description": "Allow higher memory usage",
            "disabled": false,
            "documentation_url": "https://github.com/tribe29/ansible-collection-tribe29.checkmk/blob/main/plugins/modules/rules.py"
        },
        "ruleset": "checkgroup_parameters:memory_percentage_used",
        "value_raw": "{'levels': (80.0, 90.0)}"
    },
```

```
    "response": {
        "conditions": {
            "host_labels": [],
            "host_name": {},
            "host_tags": [],
            "service_labels": []
        },
        "folder": "/",
        "folder_index": 2,
        "properties": {
            "comment": "Warning at 80%\nCritical at 90%\n",
            "description": "Allow higher memory usage",
            "disabled": false,
            "documentation_url": "https://github.com/tribe29/ansible-collection-tribe29.checkmk/blob/main/plugins/modules/rules.py"
        },
        "ruleset": "checkgroup_parameters:memory_percentage_used",
        "value_raw": "{'levels': (80.0, 90.0)}"
    }
```

**Comment by lgetwan** [comment]
I had the same problems with my latest changes. The integration test failed. But it created rules that do not match any host, so I removed the host condition. ;-) 
image
I'll now merge my PR to devel...

**Comment by lgetwan** [comment]
@geof77 Is this PR still a draft?

**Comment by geof77** [comment]
@lgetwan : yes, I would need help testing it thouroughly and it certainly needs a bit of polish...

**Comment by lgetwan** [comment]
Two weeks ahead, I have some gaps in my calendar. I hope I can have a look at this, then.

**Comment by robin-checkmk** [comment]
@geof77 could you take a look at the conflicts and fix them? Thanks!

**Pull request closed without merging**
