### PR TITLE
Feature: Introduce var env and ini variables in lookup plugins

### PR DESCRIPTION
**Pull request by msekania**
Introduce var env and ini variables in plugins.

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [X] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

one cannot specify variable like server_url and site "globally"

## What is the new behavior?

One can specify variable like server_url and site "globally", either in
- in playbook,
- in environment,
- or e.g., in ansible.cfg

**Examples:**
1: in shell
```bash
export ANSIBLE_LOOKUP_CHECKMK_SERVER_URL="https://cmkserver.example.com"
export ANSIBLE_LOOKUP_CHECKMK_SITE=test_site
export ANSIBLE_LOOKUP_AUTOMATION_USER=automation
export ANSIBLE_LOOKUP_AUTOMATION_SECRET=ABCDEFGHIJKLMNOPQRSTUVWXYZ
export ANSIBLE_LOOKUP_VALIDATE_CERTS=False
```

2: or in ansible.cfg
```ini

[checkmk_lookup]
server_url = https://cmkserver.example.com
site = test_site
automation_user = automation
automation_secret = ABCDEFGHIJKLMNOPQRSTUVWXYZ
validate_certs = False

```

Then lookup can be done as follows (example form folder lookup plugin)
```yaml
- name: Get the attributes of folder /tests
  ansible.builtin.debug:
    msg: "Attributes of folder /network: {{ attributes }}"
  vars:
    attributes: "{{ lookup('checkmk.general.folder', '~tests') }}"

```

**Another example:**
```yaml
- name: Extract some information
  hosts: localhost
  gather_facts: false
  vars:
    ansible_lookup_checkmk_server_url: "https://cmkserver.example.com"
    ansible_lookup_checkmk_site: "test_site"
    ansible_lookup_automation_user: "automation"
    ansible_lookup_automation_secret: "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    ansible_lookup_validate_certs: false

  tasks:
    - name: Get the attributes of host example.com
      ansible.builtin.debug:
        msg: "Attributes of host example: {{ attributes }}"
      vars:
        attributes: "{{ lookup('checkmk.general.host', 'exampl.com', effective_attributes=True }}"

    - name: Get the attributes of folder /tests
      ansible.builtin.debug:
        msg: "Attributes of folder /network: {{ attributes }}"
      vars:
        attributes: "{{ lookup('checkmk.general.folder', '~tests') }}"

```

## Other information

One can also define only subset of variables and at different places, e.g., some in ansible.cfg, some in console or in bashrc ...

### CODE REVIEW

**Comment by robin-checkmk** [comment]
@msekania just some quick (and somewhat lazy questions): Could one implement this as easily for the modules and maybe even for roles? I am asking, because I did not do any research yet, but playing around with it did not lead to success.

**Comment by msekania** [comment]
@robin-checkmk ,

To be honest, I haven't seen any implementation for modules or roles with this type functionality, but for lookup plugins, most lookup plugins in the Ansible collection have vars, ini and env included.
It may be related to how lookup plugins are invoked by Ansible.

**Comment by robin-checkmk** [comment]
@msekania that makes sense. I could not find anything on a quick search as well. So I think we are good here.

The integration test failures I do understand, so they are not a blocker (I think).

I want to test this a bit more and maybe do a little formatting, but from a code point of view everything should be in order. So I will line this up for the next release. Thanks!

**Comment by lgetwan** [comment]
OMG, I didn't know that it's possible to get rid of these nasty repeatedly appearing parameters. They annoyed me a lot when doing the lookup modules.
Thanks for introducing this feature! :heart:

**Review by lgetwan — APPROVED** [review]
It works fine. I tested the version lookup plugin with environment variables, ansible.ini and with local variables:
```
    - name: "Get CMK version. Use local variables."
      vars:
          ansible_lookup_checkmk_server_url: http://klapplg/
          ansible_lookup_checkmk_site: klapplg
          ansible_lookup_checkmk_validate_certs: False
          ansible_lookup_checkmk_automation_user: automation
          ansible_lookup_checkmk_automation_secret: 3f87273f-98f0-4e39-92e4-02eacd8e538a
      debug:
          msg: "Server version is {{ lookup('checkmk.general.version')}}"
      run_once: True
```

All three worked fine!

**Review by robin-checkmk — APPROVED** [review]

**Pull request merged**
