### PR TITLE
Feature parse parents attribute as list

### PR DESCRIPTION
**Pull request by msekania**
Improve Fix/Solve #515 

## Pull request type

if `parents` attribute is provided in `attributes` or `update_attributes` of host or folder module parses files as list

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

#515 
if one provides `parents: test` it would be parsed as ['t', 'e', 's', 't'] (because `parents` awaits list as a parameter)
now it will be parsed as ['test']

## What is the new behavior?

- if `parents` gets a string (or some other type) as a parameter ansible utils will take care that it will be interpreted as a list

### CODE REVIEW

**Comment by msekania** [comment]
@lgetwan, @robin-checkmk ,

this PR can be merged right away, before #536

**Comment by robin-checkmk** [comment]
Thanks for the fix @msekania! I will leave it up to @lgetwan to review the actual code, but I am very happy, then we got a handle on this!

**Review by lgetwan — COMMENTED** [review]
This change also seems to be picked into your other PR #539. I reviewed it there, but it looks slightly different, there: You're using a list FOLDER_PARENTS_PARSE, there, which even looks better. 
I'm not sure how to solve this without messing with git.

**Comment by msekania** [comment]
> This change also seems to be picked into your other PR #539. I reviewed it there, but it looks slightly different, there: You're using a list FOLDER_PARENTS_PARSE, there, which even looks better. I'm not sure how to solve this without messing with git.

@lgetwan, 

I have modified it accordingly

**Comment by lgetwan** [comment]
This PR should be merged after #539. When doing this, we might get a minor merge conflict in the folder.py, but never mind.

**Review by lgetwan — APPROVED** [review]
Thanks for implementing this, Michael!

**Pull request merged**
